# -*- coding: utf-8 -*-
"""Copy of 01_intro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13A4QxAckLSyDdqNywfMwuV04qEIoyMm8

![DSL_logo](https://github.com/BrockDSL/Intro_to_Python_Workshop/blob/master/dsl_logo.png?raw=1)


# Introduction to Python!

Welcome to the Digital Scholarship Lab introduction to Python class. By the end of today we'll know all about the following;
- variables
- math
- conditional
- loops
- functions

We'll use the Zoom's chat feature to interact.

Be sure to enable line numbers by looking for the 'gear' icon and checking the box in the 'Editor' panel.

Be sure to also 'Save a Copy' under the Edit menu.

## Python via Jupyter

- Jupyter notebooks allow us to have code in a webpage
- Each bit of code is in a 'cell', we hit the play button to run the code in the cell
- The first cell takes a bit to run because the environment is getting created
- Let's try it with the code below
"""

# We are going to ask for the user to input their name
# We'll then tell that person hello

user_name = input("What is your name? ")
print("Hello " + user_name)

"""***

## Variables, Printing and Comments

- Variable can hold values and come in different types, as we say earlier the user's name is in a variable called `user_name`
- variables can all be strings, integers, real numbers, or pretty much anything else
- when we want to print something we use the function `print()`
- Anything after a `#` is a comment, it is ignored by Python
"""

# A number with a decimal is called a real
pi = 3.14

#A number without a decimal is called an integer
items_in_a_dozen = 12

#Text in variable is called a string
favourite_color = "blue"

#You can list multiple values in one variable
#This is called a list, they can have anything in them

crayon_colours = ["red","blue","yellow"]

"""Try questions Q1 - Q3 and type "Done!" in the chat when you are finished

- **Q1** Can you create a variable called `age` and give set it to your age in years?
"""



"""- **Q2** Can you print your age to the screen?"""

print()

"""- If we want to combine things and print them all together we join them with at `+` just like we saw above

`print("Hello " + user_name)`

- **Q3** Can you modify favourite colour above, re-run the cell and complete the print statement that follows
"""

print("My name is " + user_name + " and my favourite colour is " + )

"""***

## A Python thing to keep in mind!

- Some programming languages need a `;` at the end of a line of code, not Python!
- With Python you need to **indent** your code, the rest of the examples will demonstrate this

***

## Variables - Dictionaries

- These are fancy variables
- These are a bit more complicated as they hold both a 'key' and a 'value'.
"""

phone_numbers = {
    "Mom":"555-8980",
    "Joe":"555-1021"
}

toronto_weather = {
    "Monday": 10,
    "Tuesday" : 12,
    "Wednesday" : 15,
    "Thursday" : 10,
    "Friday" : 9,
    "Saturday" : 6,
    "Sunday" : 6
    }

"""- We can print a dictionary in a very similar way to other variables like we saw earlier."""

print(phone_numbers)

"""- You can do some interesting things with dictionaries, (we'll see more as time goes on)
- For example you can print out different parts of the dictionary by adding in a `key`
"""

print(toronto_weather["Monday"])

"""Try questions Q4-Q6 below and type "Finished!" in the chat when you are done.

- **Q4** Print Wednesday's weather
"""



"""- **Q5** Print Saturday's weather"""



"""- **Q6** Print Joe's phone number"""



"""***

## Doing Math

As you'd expect with a programming language Python is pretty good at doing math. The basic operators you can use are as follows:

- `*` is for multiplication
- `+` is for addition
- `-` is the subtraction
- `%` is the remainder
- `/` is division

Let's re-use our dictionary variable about the weather from earlier.

- Let's find the average recorded for the weekdays
- Another Python hint, if you need to go across multiple lines use `\` like in the following
"""

five_day_total = toronto_weather["Monday"] + \
                    toronto_weather["Tuesday"] + \
                    toronto_weather["Wednesday"] + \
                    toronto_weather["Thursday"] + \
                    toronto_weather["Friday"]

print(five_day_total / 5)

"""- All of our temp data is in **C**
- What if we want to know it in **F**?
"""

print(toronto_weather["Monday"] * 9/5 + 32)

"""Try questions Q7 - Q10 and type "Completed" in the chat box when you are done.

- **Q7** Can you print out Thursday's temp in F?
"""



"""- **Q8** Can you print out the average temp from the weekend?"""



"""- **Q9** Can you print how many days you've been alive for (approximately) using the `age` variable?"""

age = 
print()

"""- **Q10** If you had 45 donuts and you were putting them in boxes that could hold 12 donuts, how many donuts would be in the last box?"""

lastbox =
print(lastbox)

"""*** 

## Loops 

- When we want to repeat the same thing over and over again we put it in something called a loop
- Python lets you do **a lot** with loops without typing in much text
- Here `crayon` is a variable that gets assigned to the next item in the `crayon_colours` list every time we loop
- Let's print the contents of our list using a loop
"""

crayon_colours = ["red","blue","yellow"]

for crayon in crayon_colours:
    print(crayon)

"""- The basic structure of a loop for us looks like the following

```
for item in loopable_variable:
    #do this code
```

- `item` is the variable you use every time you loop
- `loopable_variable` is the variable you'd like to loop through. Often a list, but it can be anything that Python knows how to loop through. For example strings and dictionaries as we will see soon

### Counting with Loops

Very often we use loops to count things. Each time through the loop we update a running value or we increment a counter. The following couple of cells illustrate this.
"""

candy_bars = ["Mars","Snickers","Kit Kat","Butterfinger"]

#This is a counter variable
#We'll increase this value by 1 every time we loop
total_candy_bars = 0


for bar in candy_bars:
    total_candy_bars = total_candy_bars + 1


print("Total Candy Bars: ", total_candy_bars)

"""In this example line **9** is a bit different. It is a shorthand for line **9** in the cell above. Does it make sense to you?"""

candy_bars = ["Mars","Snickers","Kit Kat","Butterfinger"]

#This is a counter variable
#We'll increase this value by 1 every time we loop
total_candy_bars = 0

#Our first code shortcut. a += b  means a = a + b 
for bar in candy_bars:
    total_candy_bars += 1


print("Total Candy Bars: ", total_candy_bars)

"""Try questions Q11 - Q13 and type "All done" into the chat box

- **Q11** Can you write a loop to print all of the numbers in the list `numbers`?
"""

numbers = [1,2,3,4,5]

for digit :

"""- **Q12** Can you make a loop that prints all of the letters in your name?"""

user_name = ""
for in user_name:

"""- **Q13** Can you write a loop that counts the number of letter in the string variable `alphabet` and print that to the screen?"""

alphabet = "abcdefghijklmnopqrstuvwxyz"

letter_count = 0

for letter in :
    

print("Total letters: ", letter_count)

"""***

## Dictionaries and Loops

- Watch what happens when we try to do a loop through a dictionary
"""

for day in toronto_weather:
    print(day)

"""- Since dictionaries are more complex, there are many ways to interact with them
- We add `.values()` to get the values of the dictionary
- We add `.keys()` to get the keys of the dictionary
"""

#print all the items in our Dictionary

for item in toronto_weather.values():
    print(item)

# print out the keys in our Dictionary

for item in toronto_weather.keys():
    print(item)

"""***

## Conditionals 

- When we want to run a piece of code only if something is true


- We can compare with the following:
 - `==`
 - `>=`
 - `<=`
 - `<`
 - `>` 
 - `!=`
 
 
 
 - When we just want to check one `condition` and if is true run `code1`
```

        if condition:
            code1
```





 - When we just want to check one `condition` and if is true run `code1`, if it is not true we run `code2` instead

```

        if condition:
            code1
        else:
            code2       
 ```

- Let's pretend that anything over 10 degrees is hot. Let' make a conditional that prints out if it is hot on **Wednesday**
"""

if toronto_weather["Wednesday"] > 10:
    print("Hot out today")

"""Try questions Q14-Q15 and type "check" into the chat box when you are done

- **Q14** Can you complete the following to make it print out "It is cold" when it is less then 10 degrees?
"""

if toronto_weather["Sunday"] 10:
    print("It is cold")

"""- **Q15** Can you write a loop that goes through all of the days of the week and prints 'Hot out Today' if the tempurature is above 10, and 'It is cold' if it is below or equal to 10 degrees?"""

for temp in toronto_weather.values():
    
    if temp 10:
        print("")
    else:
        print("")

"""***

## Combining with boolean

- Sometimes we want to combine conditionals because we want to test more complicated things
- We can do this with the following:
 - `and`
 - `or`
 - `not`

- Here's a quick game that demonstrates this
- It will ask you to put a value in between 1 and 10. If you don't, it will let you know
"""

#we can turn a variable into a integer with the int() function
number = int(input("Pick any number between 1 - 10: "))

if number > 10 or number < 1:
    print("Sorry you didn't pick a number between 1 - 10")
else:
    print("Your number is between 1 and 10!")

"""Try questions Q16, type "all done" when completed.

- **Q16** Can you re-write the conditional from the game above to use an `and` to do the same thing? you'll need to use some operators from the **Conditionals** section above. 

**HINT** It will be easier if you use <= and >=
"""

#we can turn a variable into a integer with the int() function
#as with most programming tasks there are more then 1 way to accomplish something
number = int(input("Pick any number between 1 - 10: "))

if number and number :
    print("Your number is between 1 and 10!")
else:
    print("Sorry you didn't pick a number between 1-10")

"""***

## Functions

- Functions are bits of code that do a certain task in a certain way
- We saw this earlier with the `print()` function
- We also just used the `int()` function in our game
- some functions need _arguments_ or _paramaters_. We pass those in the the round brackets. EG. we pass what string variable we want turned into an integer with the `int()` function.
- we can create our own functions too
"""

print("hello world")
int(number)

"""- A useful function is `len()` which tells you how long something is
- Let's print how long our `user_name` is
- Often a function can be applied to different types of variables and the results are ares you expect
"""

len(user_name)

"""A big part of programming is remembering function names!

- **Q18** What would the following snippet print on the screen? (Try to figure it out before running it, put your answer in the chat)
"""

len(toronto_weather)

"""The structure of a function looks like the following:


```
def name_of_function(arguments):
    #code
    #code
    return answer #not mandtory, only if you need to calculate a value
    
```
When our function produces a value that we use later we make use of `return`. That will pass the variable back to the place that called it. 



We've already seen how we call a functon:

```
name_of_function(arguments)

```

If you would like to print out the results of your function you need to surround it with the `print` function

```
print(name_of_function(arguments))

```

The next code cell demostrates this diffence.
"""

spock = "Dr. Spock"

#a function that doesn't return a value
def salute(name):
    print("Saluting " + name)

    
#a function that does return a value
def count_name_length(name):
    return len(name)


#calling our functions

salute(spock)

print(count_name_length(spock))

"""Let's reload our toronto weather data and create a function to help us analyze it better."""

toronto_weather = {
    "Monday": 10,
    "Tuesday" : 12,
    "Wednesday" : 15,
    "Thursday" : 10,
    "Friday" : 9,
    "Saturday" : 6,
    "Sunday" : 6
    }

"""- The function below will change the temp to **F** from **C**
- Statements can get pretty long if you call lots of functions in them
- Here we find **Monday's** temp in **F** and print it
"""

def temp_to_f(c):
    return c * 9/5 + 32

print(temp_to_f(toronto_weather["Monday"]))

"""Try question Q19. Type "I'm finished!" into the chat when you are done

- **Q19** Can you complete this function that finds the average temperature for the week? You just need to modify line 10.
"""

def week_avg_c(toronto_weather):
    
    total_degrees  = 0
    
    for day in toronto_weather.values():
        total_degrees = total_degrees + day
    
    #total_degrees has the sum of all 7 days of temp readings
    #you just need to modify the next line: 
    return total_degrees 

print(week_avg_c(toronto_weather))

"""----

## All the pieces together

**Q20** Here's a bit of code that has all the pieces we've looked at in it:

- loops
- conditionals
- functions
- math

The part that is new here is that we are returning two values from our function

See if you can complete the code chunk, keeping in mind what we've learned. You'll need to modify line:
*12*, *14*, *15*, *17*, & *20*


When you get the solution type "Finally Done!" into the chat box.
"""

data_points = ["Dr. Spock", "Captain Kirk", "Mr. Sulu", "Bones"]


def longest(data):
    
    max_length = 0
    max_item = ""
               
    for d in data:
               
        if len(d)  max_length:
            
            max_length = 
            max_item = 
    
    return max_item,max_length


winner = longest()

print("Longest data point is: " + str(winner) )

"""***

# Congrats! #

You now know the basics of Python, why not try some of the next workshops in the series:

- [Python for Data Science](https://brockdsl.github.io/Python_2.0_Workshop/)
- [Machine Learning with Python](https://brockdsl.github.io/Machine_Learning_with_Python/)
- [Text Analysis with Python](https://brockdsl.github.io/Text_Analysis_with_Python/)

To sign-up for future sessions please check us out on [Eventbrite](https://brockdsl.eventbrite.com)

## Further Reading

Now that we've handled the basics here are some interesting next steps you can persue.

[Kaggle](https://www.kaggle.com/) - An online portal that teaches data science using Notebooks, also has contests for cash prizes

[Python the Hard Way](https://learntocodetogether.com/learn-python-the-hard-way-free-ebook-download/) - Don't let the name fool you, this book is a great introduction to Python and programming more generally

----

# Extra homework!

If you'd really like to cement your understanding of functions in Python please these last 3 questions.

- **Q21** Can you write a function that finds the average temp for the week but in **F**? You just need to modify line 5.
"""

def week_avg_f(toronto_weather):
    
    #You just need to add one thing to the line below
    #HINT: It is something we've seen already
    avg_temp_f = week_avg_c(toronto_weather)
    return avg_temp_f


print(week_avg_f(toronto_weather))

"""- **Q22** Can you write a function that finds the average temperature for the weekend? (Some of it is there for you) HINT: Check out question 19 for inspiration. You just need to modify lines 5 and 8."""

def weekend_avg_c(toronto_weather):

    #A weekend is Saturday and Sunday. You need to find the sum of those two temps 
    total_degrees = 0
    
    #total_degrees has the sum of the weekend temps.
    return total_degrees


print(weekend_avg_c(toronto_weather))

"""- **Q23** Can you write a function that finds the average temperature for the weekend in **F**? (Some of it is ther for you) HINT: look at Q20 for inspiration"""

def weekend_avg_f(toronto_weather):

    #You just need to change the line below
    avg_temp_f = weekend_avg_c(toronto_weather)
    return avg_temp_f


print(weekend_avg_f(toronto_weather))